name: test2
model: ResNet34
max_epoch: 4
batch_size: 64
data_augmentation: standard
mix_up: false
cut_mix: false
early_stopping_patience: 20
learning_rate: 0.05
lr_scheduler: CosineAnnealingLR
cosLR_eta_min: 1.0e-6
cosLR_t_max: 100
stepLR_gamma: 0.1
stepLR_step_size: 10
label_smoothing: 0.1
grad_clip_value: 5.0
amp_enabled: true
cbam_enabled: true
num_workers: 8
optimizer: SGD
sgd_momentum: 0.9
seed: 608
weight_decay: 5.0e-4
ema_decay: 0.999
drop_prob: null